services:

  synthetic-data-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: synthesisai/dataset-generator:latest
    container_name: synthetic-data-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./templates:/app/templates
      - ./user_configs:/app/user_configs
      - ./data:/app/data
      - ./output_datasets:/app/output_datasets
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - dataset_gen_net

networks:
  dataset_gen_net:
    driver: bridge